name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download Source file
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}